### ISSUE TITLE
indention of DrRacket will destroy the program

### ISSUE THREAD

**Issue by dannypsnl** [samth/semilit#2]
```racket
#lang semilit racket
> (define x
> (+ 3 4)
some text here
> )
```
press cmd+I will make it became
```racket
#lang semilit racket
> (define x
    > (+ 3 4)
    some text here
    > )
```
Then the reader didn't work. This is probably not related to the development of the package, more like how to avoid this situation in DrRacket :).

**Comment by samth** [comment]
I think fixing this would require writing an indenter for this language.

**Comment by dannypsnl** [comment]
Wow, does that can be customized tomize?
